### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by Biffi** [simanek/Heads-Up-Grid#6] opened 2012-05-22 14:35 UTC
Hi,

The grid shows up automatically when we resized the window.

That would be great if you can fixed that.

Thanks in advance.

I'm not the same person that Pix3lmate but we are in the same school.

**Comment by simanek** [comment] 2012-05-23 00:33
This is a duplicate of another ticket that was posted shortly before this one: https://github.com/simanek/Heads-Up-Grid/issues/5

**Closed as completed by simanek** 2012-05-23 00:33 UTC

**Comment by simanek** [comment] 2012-05-23 12:42
Thanks for submitting a issue/bug! You and another individual submitted 
the identical problem at almost the exact same time! I'll try to take a 
look this weekend while also getting reacquainted with Git/Github, which 
is long overdue.

Jason Simanek

**Comment by simanek** [comment] 2012-05-25 05:11
Hi Biffi,

I have just submitted a fix. Since you and another person submitted 
similar issues at almost the exact same time I picked one to keep, and 
it wasn't yours. For that reason I wanted to contact you directly to 
make sure you were aware of a potential fix. Please take a look here:

https://github.com/simanek/Heads-Up-Grid/issues/5

and (in case you aren't familiar with Github – I'm still learning 
myself) you can download the new version here:

https://github.com/simanek/Heads-Up-Grid/downloads

The bug/issue page describes which files were changed. Let me know via 
email or comment on the Github issue directly if this update fixes the 
problem.

Jason Simanek
